### ISSUE TITLE
"Cycle" should be defined in README

### ISSUE THREAD

**Issue by off99555** [leopd/timebudget#7]
The word cycle needs a strong definition as it can confuse people. Because it can have many ambiguous meanings. Once you define it, strictly follow your definition. Then people would be able to interpret what it means whenever they see the word in the time report.

The way I figured out what this means is by experimentally checking it. But I think we can remove this experimental time needed to figure it out.

Also, I suggest that the report is as self-explanatory as much as possible. You should include the unit like `20ms per call` or `60ms per 3 calls` instead of `??ms for 3 calls`, this can be ambiguous.

Or you can do `20ms per call (average over 3 calls)`
When I send the report to someone they should not need to have insider knowledge.

**Comment by leopd** [comment]
I agree this can be confusing.  I'll take another stab at making it more clear.
